apiVersion: v1
kind: ConfigMap
metadata:
  namespace: motorq
  name: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      -  192.168.0.1-192.168.0.250  # Change this to a free IP range on your network
