# postgres-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc          # The name of the PVC
spec:
  accessModes:
    - ReadWriteOnce           # The access mode of the volume
  resources:
    requests:
      storage: 200Mi            # The amount of storage you are requesting
  storageClassName: local-path  # The StorageClass to use, or remove this line to use the default
