apiVersion: v1
kind: Service
metadata:
  name: conference-api-service
  namespace: motorq
spec:
  selector:
    app: conference-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer